//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public interface ICRMEntities {

         DbSet<User> Users { get; set; }
      void OnModelCreating(DbModelBuilder modelBuilder);

    }



    public partial class CRMEntities : DbContext,ICRMEntities
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
          public void  OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
            
        }


        public virtual DbSet<User> Users { get; set; }
    }
}
