//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRMEntities3 : DbContext
    {
        public CRMEntities3()
            : base("name=CRMEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendedore> Vendedores { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<Ventas_x_Productos> Ventas_x_Productos { get; set; }
    
        public virtual ObjectResult<getVentas_Result> getVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getVentas_Result>("getVentas");
        }
    

    
        public virtual ObjectResult<getPropuestas2_Result> getPropuestas2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPropuestas2_Result>("getPropuestas2");
        }
    }
}
